apiVersion : apps/v1
kind: Deployment
metadata:
  name: app-82265825
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-82265825
  template:
    metadata:
      labels:
        app: app-82265825
    spec:
      containers:
        - name: app-82265825
          image: cepgbaseacr.azurecr.io/app-82265825
          ports:
          - containerPort: 8080